Remove Coveralls (#185)
* Remove Coveralls

Coveralls is currently making it impossible to merge PRs, since
they are not having the coveralls status reported. Admins also
cannot override this.

* Add cryptography dependencies

Previously, the job failed with:
"c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory"

* Remove coverage usage